### ISSUE TITLE
add a horizontal position scale to the profile graph

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#23]

**Comment by JoostZ** [comment]
Implemented a grid.. Keeping issue open until verified

**Comment by Tomhz** [comment]
I am not sure about this enhancement. Initially i asked for a horizontal position scale in the Profile Graph. I think I got convinced than position scale was hard to implement and you made a time scale. 
But with recent enhancements, maybe a position scale is possible?

**Comment by JoostZ** [comment]
The problem is not with the scale but with the graph itself. Currently the curves are a function of Velocity against Time. Adding a horizontal position scale would then not be linear. For instance, with the default settings the handle moves forward at the beginning of the stroke (negative handle velocity) and so there would be two points on the graph that have the same position. Also, the different curves have a different position scale.

I suppose it would be possible to plot the curves as a function of velocity against, e.g., the position of the handle. But this would change the shape of the curves. Again, looking at the handle, the curve would start going to the left.

I am wondering what is plotted in the literature. I don't know any references anymore. Do you still have examples?

Anyway, if you want a change I propose you create a new enhancement.

**Comment by Tomhz** [comment]
The literature sometimes uses time and sometimes percentage (of what?). So indeed i don't think using a horizontal distance scale will add anything. And I have enhancement #24 that wil give me distance information in the animation. 
So I will close this issue.
