### ISSUE TITLE
After loading an RWA file, changes from the segments editor are not shown in Animation

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#34]
But they are shown correctly in the segments definition.  
It works good when working with the default, right after starting the program.

**Comment by Tomhz** [comment]
This one has relative high prio.

**Comment by JoostZ** [comment]
It is possible to show priority by reordering the issues in the list. See https://github.com/blog/2206-reorder-issues-within-a-milestone

**Comment by JoostZ** [comment]
I am assuming that the problem here is that loaded segment definitions are not reflected in the segment editor. Indeed, the segment editor is always using the default settings. This also means that changing anything in the editor will be reflected in the default segments and those are not used by the animation :(.

If there was a way to create a new document, which would use the default settings, then we would see the result of the editor. Not what we want.

**Comment by JoostZ** [comment]
Fixed. Ready for testing in next development build

**Comment by Tomhz** [comment]
Works OK now
