### ISSUE TITLE
after using SegmentEditor, changing segment limits in "animation settings" leaves the changed segment unchanged

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#39]
This leads to jerky movements at the beginning or end of stroke.  
I will try to find out what circumstances

**Comment by Tomhz** [comment]
Found it: after using segment editor on a Stroke segment it is possible to change the "from" and "To" limits in the "Animation Settings". They are not yellow (=non-changeable) anymore. This is undesirable anyway because these limits should be the same as the corresponding segments in the Recovery. I think I should make a separate issue for that.

Anyway, from this situation, when you change parameters in the Limits box they are only changed in the yellow segment, not in the segment that was changed using the segmenteditor.

**Comment by JoostZ** [comment]
I had noticed this behavior that fields turned white. However, I did not address this issue because I was wondering if we should keep the segment list in the Animation Settings now that we have the Segment Editor. We could consider to replace the segment list by the segment editor in the tab. What do you think? Do you still want to use the editing of the fields in the Animation Settings?

**Comment by Tomhz** [comment]
At the moment I don't think we should drop the Segment List. 
But now that we have the Segment editor I don't need to edit the To/From  fields in the Animation Settings anymore, 
The problem is that after a segment field has changed from Yellow to White the To/From fields are not synchronised anymore with Limits parameters wich may lead to difference between corresponding Stroke and recovery segments and jerky movements.

**Comment by Tomhz** [comment]
I think this is solved now. See closed bug #43. I will keep it open in order to do a little more testing on this issue.
