### ISSUE TITLE
Allow the display of a second rower that animates simultaneously.

### ISSUE THREAD

**Issue by JoostZ** [JoostZ/ShowRow#46]
This would allow to have a reference rower, that would probably be a 'correct' stroke and compare with another rower to more clearly see what is 'wrong'.

The idea would be to allow loading of a .rwa file for such a reference rower.

**Comment by Tomhz** [comment]
This would be very usefull. Especially now that we can change Tempo without messing up the segments

**Comment by JoostZ** [comment]
@Tomhz Question about this.   

My plan is to load a .RWA file for the 'reference rower', i.e., the second rower that will be displayed. The saved .RWA files contain all information regarding the animation. What if some of the information for the reference rower does not match the animated rower?

The Limits parameters should definitely be taken from the reference .rwa since it controls the movement. The Timing information should be taken from the original rower since we want to keep the movement synchronous.

But what about the static parameters? We could use the static data from the original rower. That way the shape of the two rowers would be the same. But would the definition of the segments have to change if static parameters are changed? In that case we need to take the static parameters from teh reference rower.

What do you think?

**Comment by Tomhz** [comment]
This is a difficult subject. I think it all depends on what you want to show as a coach/instructor  when putting both animations side by side. 

For a start, I think you should only match Tempo and the timing of the catch (gelijke inpik).  
After implementing this, I might get some new ideas about matching both animations automatically.

Changing static parameter automatically seems not a good idea. It could be interesting to show how a taller rower changes his limits in order to match catch and release of the smaller rower

Another idea would be to save both animations in a single RWA-file after matching limits an timings manually. But that ofcourse is another Enhancement Issue.

**Comment by JoostZ** [comment]
Implemented the display of a second RWA file.

Does not yet allow saving the reference image to PNG or GIF. We should open a new issue for that. We also can use a new issue for any bugs or wished for enhancements.

**Comment by Tomhz** [comment]
This is a very useful enhancement.  I didn't think of the overlay solution yet, but this is better than showing both rowers side by side.
I think we can close this issue now and make new issues for bugs and enhancements. Do you agree?

**Comment by JoostZ** [comment]
Agree. Closed it.
