### ISSUE TITLE
There is an extra horizontal line in the animation when the "Animation Setting" Tab is selected in the left screen

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#56]
This extra line is below the four lines that are visible in the animation

**Comment by JoostZ** [comment]
This comes from the scaling of the rower figure. The Animation Setting Tab is wider then the other two control tabs and, as a consequence, there is less room for the animation and the rower is scaled. Since I want to keep the aspect ratio the same, the vertical size of the rower no longer fills the whole space and you see the bounding box of the rower image. You get the same result if you resize the total window (making it smaller) and you can get rid of it when you make the window wider.

I could get rid of the bounding box but then the grid lines could end on nothing. Or I could give the border a different color.

What do you think?

**Comment by Tomhz** [comment]
With my request to drop the horizontal lines I think this Issue can be closed. What do you think?

**Comment by JoostZ** [comment]
Like I said, the horizontal line is the bounding box. If I remove the horizontal lines but leave the bounding box you would still get a horizontal line if you make the window narrower. And an extra vertical line if you make the window wider.

If I remove the bounding box then the vertical lines would not be connected to the bottom (if the window gets narrower).

Hm, I just realized I can draw the vertical lines to the bottom of the graph, independent of the scaling. So shall I do that and leave out the bounding box? I will implement that in the next development build so you can see the result.

I will move this issue in 'In Progress'.

**Comment by Tomhz** [comment]
OK, that is a gooed idea

**Comment by JoostZ** [comment]
This will be included in #21
