### ISSUE TITLE
Export an animation to Animated Gif and/or MP4 files

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#60]
To be able to show animation result without the application

**Comment by Tomhz** [comment]
I find it hard to decide about priority of this (and other) issues. I would really like this functionality to be able to hand over these exports to rowers without having them to use the software. 
On the other hand, i have no idea of the time it will take you to implement. 
That dilemma is what planning poker of Agila Scrum is about.

**Comment by JoostZ** [comment]
I will spend some time investigating how much work it would be.

**Comment by JoostZ** [comment]
[This link](https://blogs.msdn.microsoft.com/saveenr/2008/09/18/wpfxaml-saving-a-window-or-canvas-as-a-png-bitmap/)shows how to save a canvas as PNG.

[This link](https://blogs.msdn.microsoft.com/saveenr/2008/09/22/wpfxaml-saving-an-animation-as-an-avi-video-file/ ) shows how to combine such immages to a movie.

[This link](https://stackoverflow.com/questions/17693516/saving-a-wpf-canvas-as-an-image-following-mvvm-pattern) shows how to save a canvas from the View Model.

**Comment by JoostZ** [comment]
This issue has two aspects:

1.  Extract the image from the Animation Window
1. Combine a sequence of these images into a movie.

The first task is fact independent of the second. Therefore I have decided to create a new issue (#65) to do task 1. Then task 2 will be done under this issue.

**Comment by JoostZ** [comment]
I am able to extract an animated GIF now. However, the process is verys low _and_ blocks the UI. Sp I am now trying to find out how I can do the creation of the GIF in the background.
![rowanimation](https://user-images.githubusercontent.com/4018815/33030428-94c0a38e-ce1b-11e7-877e-629835e28f22.gif)

**Comment by JoostZ** [comment]
Got it to work in the background. Now need to make it more robust and controllable.

**Comment by Tomhz** [comment]
Nice. I will wait for your results

**Comment by JoostZ** [comment]
I have 'released' a preliminary build with this functionality. It is still somewhat rough but I think it is a good idea for you to play with it and come back with suggestions for improvement and what goes wrong. My proposal is that, unless there is a serious bug, to close this issue and open new issues for any improvements and bugs.

Some notes about the use.

If you click on the Save button in the Row Animation tab then a dialog box is opened where you can specify some details for the save.

- The radio buttons allow to select saving the current shown image as PNG or to save the whole Stroke as an animated GIF.
- If saving as GIF you can specify the frame rate and the quality. A quality of 0 is the highest quality but also the slowest is saving. Apparently a value > 25 will not improve the speed.
- The Width and Height specify the size of the saved image. If 'Keep Aspect Ratio' is checked then the ratio between Height and Width remain to have a 'natural' size of the image. Unchecking it and having a different ratio you will use only part of the saved image for the actual image, since the save will scale the image to fit in the specified Width and Height but will not distort the form. So I think it should always remain checked.
- You can select the file to save to by clicking on the Browse button.
- You can cancel the save operation by clicking on the Cancel button. But for now this can only be done before the Save button is clicked.
- In saving to GIF a progress bar will show, telling how far the save is gone. For the save to PNG this is not shown since the save is quick enough.
- When the save is completed (either type) the the window will automatically close.

**Comment by Tomhz** [comment]
I agree to close this issue as saving works as a rough solution 
During the process of more accurate testing i will need to reread you previous comment.
