### ISSUE TITLE
Why can't I increase T0 of the right subsegment in this segment editor session? 

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#67]
Why is there an upper limit of 0.74 on T0? Is this a bug?

![rowanimation_8](https://user-images.githubusercontent.com/5354652/32983291-a48b77a6-cc92-11e7-859e-f67f32dc7c43.png)

**Comment by JoostZ** [comment]
If I look at this image I understand the upper limit of T0. T3 is at the end value so if you moved T0 to the right T3 would move over the limit.

What seems to be wrong is that the lower limit is 0.56. It should not be possible to move the sub-segment to the left since the sub-segment already touches the previous segment.

This is probably related to #54 and #55.

**Comment by Tomhz** [comment]
Moving the T3 of the right subsegment to the left does not help. T0 still has a maximum limit  of 0.74. 
But: after saving and reopening the Segment Editor for this segment this limit is higher and I can move T0 to the right. So this actually is a bug. I hope you have enough information. I can investigate a bit more and attach a RWA file if you want.
 
When i move the T3 further down (to the left) I easily run in #55

**Comment by Tomhz** [comment]
I assume, not being able to increase T0 is not the bug. That should be overcome by decreasing T3 first. 
The bug is the fact that decreasing T3 does not increase the maximum of T0. At least not until I save and reopen the Segment editor. 
What do you think, should I create a new Bug-issue, or change the title of this question-Issue?

**Comment by Tomhz** [comment]
I do not agree with your remark about the minimum limit of T0 being wrong. The current value is 0.74 and the minimum limit is 0.56. There is still some "room" between T0 of the right subsegment and T3 of the left subsegment

**Comment by JoostZ** [comment]
OK, I thought from looking at the image that T0 of the right segment was touching the T3 of the first sub-segment. That meant that the 0.56 was wrong (should have been 0.74). Looking closer at the image I can see that the 0.56 is probably right.

I still think that this issue is closely related to #54 and #55 so I don't want to have a different issue now.  I think that the basic problem in all three issues is that the limits are not displayed correctly. However, these limits are enforced in the sliders.

Can you attach a .rwa that creates the above image?

**Comment by JoostZ** [comment]
Changing T3 (or Duration) did not update the upper limit of T0. Fixed now.

**Comment by Tomhz** [comment]
I agree this is fixed now. I will take a new look at #54 and #55
